import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useState } from "react";
import axios from 'axios';


const API_ENDPOINT = 'http://localhost:8000/'
export const config = {
  api: {
    bodyParser: false,
  },
}

function Home({ data }) {

  return (
    <div>
      <Head>
        <title>Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    
    )
  }
  

export default Home