import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useState } from "react";
import axios from 'axios';


const API_ENDPOINT = 'http://localhost:8000/'
export const config = {
  api: {
    bodyParser: false,
  },
}

async function load_pic() {
  const url = 'http://127.0.0.1:8000/predict/tsne-image'
  const options = {
      method: "GET"
  }

  let response = await fetch(url, options)

  if (response.status === 200) {
      const imageBlob = await response.blob()
      const imageObjectURL = URL.createObjectURL(imageBlob);

      const image = document.createElement('img')
      image.src = imageObjectURL

      const container = document.getElementById("your-container")
      container.append(image)
  }
  else {
      console.log("HTTP-Error: " + response.status)
  }
}

function Home({ data }) {

  const myLoader = ({ src, width, quality }) => {
    return `http://127.0.0.1:8000/predict/tsne-image`
  }
  const [image, setImage] = useState(null);
  const [createObjectURL, setCreateObjectURL] = useState(null);

  const uploadToClient = (event) => {
    if (event.target.files && event.target.files[0]) {
      const i = event.target.files[0];

      setImage(i);
      setCreateObjectURL(URL.createObjectURL(i));
    }
  };

  return (
    <div>
      <Head>
        <title>Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    
    )
  }
  

export default Home