import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>Upload Data</div>
      <form action="/action_page.php">
        <input type="file" id="myFile" name="filename"/>
        <input type="submit"/>
      </form>

    </div>
  )
}
