import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
// import Loading from './loading'
import { Suspense } from 'react'


function Images() {
  const myLoader = ({ src, width, quality }) => {
    return `http://127.0.0.1:8000/predict/tsne-image`
  }
  return (

    <div className="bg-fuchsia-50 p-2 h-full">
      <Head>
        <title>Project Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex gap-4 '>
        <Link href="/">Back</Link>
        <div>T-SNE</div>
      </div>
      <Suspense fallback={<Loading/>}>
        <Image
          loader={myLoader}
          src="/"
          alt="T-SNE Projection"
          width={500}
          height={500}


        />
      </Suspense>

    </div>
  )
}
function Loading() {
  return <h2>🌀 Loading...</h2>;
}
export default Images;
  